@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueLessonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueLessonList
UniqueTagList -[hidden]down- UniqueLessonList

UniqueTagList -right-> "*" Tag
UniqueLessonList -right-> lesson

lesson -up-> "*" Tag

lesson *--> Name
lesson *--> Phone
lesson *--> Email
lesson *--> Address
@enduml
